[package]
name = "zk-tlock"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
ark-ff = { version = "^0.3.0", default-features = false }
ark-ec = { version = "^0.3.0", default-features = false }
ark-std = { version = "^0.3.0", default-features = false }
ark-snark = { version = "^0.3.0", default-features = false }
ark-r1cs-std = { version = "^0.3.0", default-features = false, optional = true }
ark-relations = { version = "^0.3.0", default-features = false, optional = true}
ark-groth16 = { version = "^0.3.0", features = ["r1cs", "std"] }
ark-sponge = { version = "^0.3.0" , features = ["r1cs"] }
ark-serialize = { version = "^0.3.0", default-features = false }
ark-ed-on-bls12-381 = { version = "^0.3.0", default-features = false, features = [ "r1cs" ] }
ark-bls12-381 = { version = "^0.3.0" }

pretty_env_logger = "0.4.0"
tracing = { version = "0.1", default-features = false, features = [ "attributes" ] }

json = "0.12.4"
lazy_static = "^1.4.0"
serde_json = "1.0.82"
hex = "0.4.3"

[features]
default = [ "std", "parallel", "r1cs" ]
std = [ "ark-ff/std", "ark-ec/std", "ark-std/std", "ark-relations/std", "ark-serialize/std" ]
r1cs = [ "ark-relations", "ark-r1cs-std" ]
parallel = [ "std", "ark-ff/parallel", "ark-ec/parallel", "ark-std/parallel"]
